version: 1.0.{build}
branches:
  only:
  - develop
  - master
image: Ubuntu2004
build:
  verbosity: normal

environment:
  COVERALLS_SERVICE_NAME: appveyor 
  COVERALLS_REPO_TOKEN: gTsNEOQHWMPIKEvTRBW6KPn6xUuAIZcof

init:
    - sudo apt-get update -y --allow-releaseinfo-change
    - sudo apt-get install -qq python3-pip
    
install: 
    - python3 -m pip install --upgrade pip
    - python3 -m pip install --upgrade numpy
    - python3 -m pip install --upgrade scipy
    - python3 -m pip install --upgrade scikit-learn
    - python3 -m pip install --upgrade importlib_metadata 
    - python3 -m pip install --upgrade matplotlib
    - python3 -m pip install --upgrade plotly
    - python3 -m pip install --upgrade kaleido
    - python3 -m pip install --upgrade pandas
    - PATH=$PATH:/home/appveyor/.local/bin
    - python3 setup.py develop --user 
    - cd RCAIDE
    - PATH=$PATH:/home/appveyor/.local/bin/RCAIDE
    - python3 -m pip install coveralls==3.2.0
    - cd ..
    - cd Regressions
    
test_script:
  coverage run automatic_regression.py test
     
on_success:
  coveralls
